### ISSUE TITLE
i40e 2.27.8 doesn't compile with Linux 6.14

### ISSUE THREAD

**Issue by neverstopdreaming** [intel/ethernet-linux-i40e#14]
**Driver Tag/Commit**
https://github.com/intel/ethernet-linux-i40e/releases/tag/v2.27.8

**OS Platform and Distribution**
Proxmox 8.4.1 - Kernel 6.14.0-2

**Bug description**
Interl i40e driver 2.27.8 does not compile with kernel 6.14 on Proxmox
On kernel 6.8 it compiles without error

**Relevant log output**
```
*** The target kernel has CONFIG_MODULE_SIG_ALL enabled, but
*** the signing key cannot be found. Module signing has been
*** disabled for this build.
make[1]: Entering directory '/usr/src/linux-headers-6.14.0-2-pve'
make[2]: Entering directory '/root/i40e-2.27.8/src'
  CC [M]  i40e_main.o
i40e_main.c:15339:35: error: initialization of ‘int (*)(struct ndmsg *, struct nlattr **, struct net_device *, const unsigned char *, u16,  u16,  bool *, struct netlink_ext_ack *)’ {aka ‘int (*)(struct ndmsg *, struct nlattr **, struct net_device *, const unsigned char *, short unsigned int,  short unsigned int,  _Bool *, struct netlink_ext_ack *)’} from incompatible pointer type ‘int (*)(struct ndmsg *, struct nlattr **, struct net_device *, const unsigned char *, u16,  u16,  struct netlink_ext_ack *)’ {aka ‘int (*)(struct ndmsg *, struct nlattr **, struct net_device *, const unsigned char *, short unsigned int,  short unsigned int,  struct netlink_ext_ack *)’} [-Werror=incompatible-pointer-types]
15339 |         .ndo_fdb_add            = i40e_ndo_fdb_add,
      |                                   ^~~~~~~~~~~~~~~~
i40e_main.c:15339:35: note: (near initialization for ‘i40e_netdev_ops.ndo_fdb_add’)
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-6.14.0-2-pve/scripts/Makefile.build:207: i40e_main.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.14.0-2-pve/Makefile:1999: .] Error 2
make[2]: *** [/usr/src/linux-headers-6.14.0-2-pve/Makefile:251: __sub-make] Error 2
make[2]: Leaving directory '/root/i40e-2.27.8/src'
make[1]: *** [Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.14.0-2-pve'
make: *** [Makefile:76: default] Error 2
```

**Comment by Adam-Vandervorst** [comment]
Right, I believe https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4b42fbc6bd8f73d9ded535d8c61ccaa837ff3bd4 is the relevant commit.

**Comment by JonKohler** [comment]
Have you tried the new one yet? https://github.com/intel/ethernet-linux-i40e/releases/tag/v2.28.5
