### ISSUE TITLE
2.28.13 does not compile for kernel 6.17.2-2

### ISSUE THREAD

**Issue by bastian433** [intel/ethernet-linux-i40e#25]
Unfortunately I am not able to compile version 2.28.13 for kernel 6.17.2-2

It does work in kernel 6.14.11-4

```
Autoinstall of module i40e/2.28.13 for kernel 6.17.2-2-pve (x86_64)
Building module(s)....(bad exit status: 2)
Failed command:
make -j16 KERNELRELEASE=6.17.2-2-pve -C /lib/modules/6.17.2-2-pve/build M=/var/lib/dkms/i40e/2.28.13/build

Error! Bad return status for module build on kernel: 6.17.2-2-pve (x86_64)
Consult /var/lib/dkms/i40e/2.28.13/build/make.log for more information.
```
Logfile:

```
DKMS (dkms-3.2.2) make.log for i40e/2.28.13 for kernel 6.17.2-2-pve (x86_64)
Sat Nov 29 12:06:32 AM CET 2025

Building module(s)
# command: make -j16 KERNELRELEASE=6.17.2-2-pve -C /lib/modules/6.17.2-2-pve/build M=/var/lib/dkms/i40e/2.28.13/build
make: Entering directory '/usr/src/linux-headers-6.17.2-2-pve'
make[1]: Entering directory '/var/lib/dkms/i40e/2.28.13/build'
  CC [M]  i40e_main.o
  CC [M]  i40e_ethtool.o
  CC [M]  i40e_xsk.o
  CC [M]  i40e_adminq.o
  CC [M]  i40e_common.o
  CC [M]  i40e_hmc.o
  CC [M]  i40e_lan_hmc.o
  CC [M]  i40e_nvm.o
  CC [M]  i40e_debugfs.o
  CC [M]  i40e_diag.o
  CC [M]  i40e_txrx.o
  CC [M]  i40e_ptp.o
  CC [M]  i40e_filters.o
  CC [M]  i40e_ddp.o
  CC [M]  i40e_client.o
  CC [M]  i40e_virtchnl_pf.o
  CC [M]  i40e_dcb.o
  CC [M]  i40e_dcb_nl.o
  CC [M]  kcompat.o
  CC [M]  kcompat_vfd.o
i40e_main.c: In function ‘i40e_service_timer’:
i40e_main.c:12468:30: error: implicit declaration of function ‘from_timer’; did you mean ‘mod_timer’? [-Wimplicit-function-declaration]
12468 |         struct i40e_pf *pf = from_timer(pf, t, service_timer);
      |                              ^~~~~~~~~~
      |                              mod_timer
i40e_main.c:12468:48: error: ‘service_timer’ undeclared (first use in this function); did you mean ‘i40e_service_timer’?
12468 |         struct i40e_pf *pf = from_timer(pf, t, service_timer);
      |                                                ^~~~~~~~~~~~~
      |                                                i40e_service_timer
i40e_main.c:12468:48: note: each undeclared identifier is reported only once for each function it appears in
i40e_main.c: In function ‘i40e_init_recovery_mode’:
i40e_main.c:17569:9: error: implicit declaration of function ‘del_timer_sync’; did you mean ‘dev_mc_sync’? [-Wimplicit-function-declaration]
17569 |         del_timer_sync(&pf->service_timer);
      |         ^~~~~~~~~~~~~~
      |         dev_mc_sync
i40e_main.c: In function ‘i40e_set_udp_tunnel_callbacks’:
i40e_main.c:17625:36: error: ‘UDP_TUNNEL_NIC_INFO_MAY_SLEEP’ undeclared (first use in this function); did you mean ‘UDP_TUNNEL_NIC_INFO_IPV4_ONLY’?
17625 |         pf->udp_tunnel_nic.flags = UDP_TUNNEL_NIC_INFO_MAY_SLEEP;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                    UDP_TUNNEL_NIC_INFO_IPV4_ONLY
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: i40e_main.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/linux-headers-6.17.2-2-pve/Makefile:2016: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.17.2-2-pve/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/i40e/2.28.13/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.17.2-2-pve'

# exit code: 2
# elapsed time: 00:00:04
```

**Comment by JonKohler** [comment]
You'll need to make a few very small tweaks to the i40e source to make it work, but its trivial

6.17 API change: https://github.com/torvalds/linux/commit/1ead7501094c6a61461c0c98dde9ec5660fa1e24 `udp_tunnel: remove rtnl_lock dependency` <- one line change to remove `pf->udp_tunnel_nic.flags = UDP_TUNNEL_NIC_INFO_MAY_SLEEP;`
6.15 API change: https://github.com/torvalds/linux/commit/8fa7292fee5c5240402371ea89ab285ec856c916 `treewide: Switch/rename to timer_delete[_sync]()` <- 5 line change to convert `del_timer_sync` to `timer_delete_sync`

and while I'm at it, 6.18 changes: https://github.com/torvalds/linux/commit/c8a09fc9664f79eeb66cdf4a2a34d5b6a239b727 `ida: remove the ida_simple_xxx() API`

**Comment by bastian433** [comment]
Thank you, but commenting out udp_tunnel_nic.flags = UDP_TUNNEL_NIC_INFO_MAY_SLEEP; and renaming the 5 del_timer_sync to timer_delete_sync leaves this error:

```
i40e_main.c: In function ‘i40e_service_timer’:
i40e_main.c:12468:30: error: implicit declaration of function ‘from_timer’; did you mean ‘mod_timer’? [-Wimplicit-function-declaration]
12468 |         struct i40e_pf *pf = from_timer(pf, t, service_timer);
      |                              ^~~~~~~~~~
      |                              mod_timer
i40e_main.c:12468:48: error: ‘service_timer’ undeclared (first use in this function); did you mean ‘i40e_service_timer’?
12468 |         struct i40e_pf *pf = from_timer(pf, t, service_timer);
      |                                                ^~~~~~~~~~~~~
      |                                                i40e_service_timer
i40e_main.c:12468:48: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by bastian433** [comment]
For 2.28.15 and Proxmox kernel 6.17.4-1 the same changes still need to be made

**Comment by bastian433** [comment]
2.28.16 has the required changes for 6.17.4-2-pve (proxmox kernel)
